server:
  port: 3333
  forward-headers-strategy: framework
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
aws:
  region: us-east-1
  profile: wdyt-test
  secret-name: wdyt-test-environment
  cloudwatch:
    log-group: /wdyt/wdyt-test
    log-stream: wdyt-test
  s3:
    bucket: wdyt-test-bucket
    endpoint: https://duoymrhqgte1g.cloudfront.net
  sns:
    pushNotificationArn: arn:aws:sns:us-east-1:976193257823:app/APNS_SANDBOX/wdyt-test-push
    apnsIdentifier: APNS_SANDBOX
apple:
  storekit:
    url: https://api.storekit-sandbox.itunes.apple.com/inApps/v1/notifications/history
integrations:
  create-robot:
    url: https://test-second.the2nd.ai/api/v1/wdyt-integration/robot
  background-extraction:
    url: http://3.229.32.99:4321/bg/remove
  image-classification:
    url: http://3.229.32.99:7654/upload
  weather:
    api-key: 43837f96e63b4f89a32151818250301
chatgpt:
  version: gpt-4o-mini
spring:
  application:
    name: wdyt-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    class: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wdyt
  jpa:
    show-sql: false      # Show SQL queries in the console
    database-platform: org.hibernate.dialect.MySQLDialect
application:
  base:
    url: https://test-api.thewdyt.com
  event:
    max:
      retry:
        count: 3
    delay:
      minutes:
        after:
          produce: 5